#!/usr/bin/env python3
"""
scripts/sign_firmware.py
Compute HMAC-SHA256 of the Appli binary and update boot_hmac_tag.h.

Usage (run from repo root after 'make appli'):
    python scripts/sign_firmware.py

Then rebuild and flash Boot:
    make boot
    make flash-boot
"""

import hmac
import hashlib
import os
import sys

APPLI_BIN  = os.path.join("build", "Appli", "SecureStorage_rev1_Appli.bin")
TAG_HEADER = os.path.join("Boot", "Core", "Inc", "boot_hmac_tag.h")

# Secret 32-byte HMAC key — embedded in Boot flash, protected by RDP Level 1.
# This value must stay constant for the lifetime of the device.
# Changing it requires re-signing and re-flashing every device.
HMAC_KEY = bytes([
    0x4A, 0x7F, 0x2C, 0xB1, 0x93, 0xE8, 0x55, 0x0D,
    0xF6, 0x3A, 0xC7, 0x81, 0x2E, 0x94, 0x6B, 0x50,
    0xD3, 0x17, 0x8A, 0xCC, 0x64, 0xFB, 0x29, 0x0E,
    0x5B, 0xA4, 0x71, 0x3C, 0x88, 0xD2, 0x1F, 0x46,
])


def to_c_array(name: str, data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return (f"static const uint8_t {name}[{len(data)}] = {{\n"
            + "\n".join(lines) + "\n};")


def main():
    if not os.path.exists(APPLI_BIN):
        print(f"ERROR: {APPLI_BIN} not found — run 'make appli' first.")
        sys.exit(1)

    with open(APPLI_BIN, "rb") as f:
        appli_data = f.read()

    tag = hmac.new(HMAC_KEY, appli_data, hashlib.sha256).digest()
    appli_size = len(appli_data)

    header = f"""\
#ifndef BOOT_HMAC_TAG_H
#define BOOT_HMAC_TAG_H

/* Auto-generated by scripts/sign_firmware.py — do not edit manually.
 * Appli size : {appli_size} bytes ({appli_size / 1024:.1f} KB)
 * HMAC-SHA256: {tag.hex()}                */

/* NOR flash base address where the Appli binary is mapped. */
#define APPLI_BASE_ADDR  0x70000000UL

/* Size of the Appli binary (bytes). */
#define APPLI_SIZE       {appli_size}UL

/* 32-byte secret HMAC key — in Boot flash, protected by RDP Level 1. */
{to_c_array("HMAC_KEY", HMAC_KEY)}

/* 32-byte expected HMAC-SHA256 tag of the current Appli binary. */
{to_c_array("EXPECTED_TAG", tag)}

#endif /* BOOT_HMAC_TAG_H */
"""

    with open(TAG_HEADER, "w", newline="\n") as f:
        f.write(header)

    print(f"[sign] Appli     : {APPLI_BIN}")
    print(f"[sign] Size      : {appli_size} bytes ({appli_size / 1024:.1f} KB)")
    print(f"[sign] HMAC-SHA256: {tag.hex()}")
    print(f"[sign] Written   : {TAG_HEADER}")
    print(f"[sign] Next step : make boot && make flash-boot")


if __name__ == "__main__":
    main()
