#!/usr/bin/env python3
"""gen_cert.py — Generate self-signed RSA-2048 cert for the HTTPS bench server.

Outputs:
  server/certs/server.crt  — PEM cert  (for Python SSL server)
  server/certs/server.key  — PEM key   (for Python SSL server)
  Appli/Core/Inc/server_ca_cert.h — DER cert as C array (for mbedTLS firmware)
"""

import datetime, ipaddress, os, textwrap
from cryptography import x509
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CERTS_DIR  = os.path.join(SCRIPT_DIR, "certs")
HEADER_OUT = os.path.join(SCRIPT_DIR, "..", "Appli", "Core", "Inc", "server_ca_cert.h")
SERVER_IP  = "136.113.205.153"

os.makedirs(CERTS_DIR, exist_ok=True)

print("Generating RSA-2048 key...")
key = rsa.generate_private_key(public_exponent=65537, key_size=2048)

subject = x509.Name([
    x509.NameAttribute(NameOID.COMMON_NAME,         "SecureStorage-Bench-Server"),
    x509.NameAttribute(NameOID.ORGANIZATION_NAME,   "STM32 SecureStorage Bench"),
])

cert = (
    x509.CertificateBuilder()
    .subject_name(subject)
    .issuer_name(subject)
    .public_key(key.public_key())
    .serial_number(x509.random_serial_number())
    .not_valid_before(datetime.datetime(2026, 1, 1, tzinfo=datetime.timezone.utc))
    .not_valid_after (datetime.datetime(2036, 1, 1, tzinfo=datetime.timezone.utc))
    .add_extension(x509.SubjectAlternativeName([
        x509.IPAddress(ipaddress.IPv4Address(SERVER_IP)),
    ]), critical=False)
    .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
    .add_extension(x509.KeyUsage(
        digital_signature=True, content_commitment=False,
        key_encipherment=True, data_encipherment=False,
        key_agreement=False, key_cert_sign=True,
        crl_sign=False, encipher_only=False, decipher_only=False,
    ), critical=True)
    .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False)
    .sign(key, hashes.SHA256())
)

cert_pem = os.path.join(CERTS_DIR, "server.crt")
key_pem  = os.path.join(CERTS_DIR, "server.key")

with open(cert_pem, "wb") as f:
    f.write(cert.public_bytes(serialization.Encoding.PEM))
with open(key_pem, "wb") as f:
    f.write(key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.TraditionalOpenSSL,
        serialization.NoEncryption(),
    ))

print(f"  cert: {cert_pem}")
print(f"  key:  {key_pem}")

# C header with DER-encoded cert
der   = cert.public_bytes(serialization.Encoding.DER)
lines = []
for i in range(0, len(der), 16):
    chunk = der[i:i+16]
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

header = f"""\
#ifndef SERVER_CA_CERT_H
#define SERVER_CA_CERT_H

/* Auto-generated by server/gen_cert.py — do not edit manually.
 * Self-signed RSA-2048 / SHA-256 certificate for {SERVER_IP}:8443.
 * Embed as trusted CA in the firmware (mbedTLS x509_crt_parse_der). */

static const unsigned char SERVER_CA_CERT_DER[] = {{
{chr(10).join(lines)}
}};

static const unsigned int SERVER_CA_CERT_DER_LEN = sizeof(SERVER_CA_CERT_DER);

#endif /* SERVER_CA_CERT_H */
"""

with open(HEADER_OUT, "w", newline="\n") as f:
    f.write(header)

print(f"  hdr:  {HEADER_OUT}  ({len(der)} bytes DER)")
print(f"  Serial : {cert.serial_number}")
print(f"  Valid  : {cert.not_valid_before_utc.date()} → {cert.not_valid_after_utc.date()}")
print("Done.")
